server:
  port: 8008
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: test-service
          uri: http://localhost:8080/
          predicates:
            - Path=/test/**
          filters:
            - AuthenticationFilter
logging:
  level:
    '[org.springframework.cloud.gateway]': TRACE

jwt:
  secret: testing
  validity: 20
  authDisabled: false